### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by SirMonkeyBoy** [JACOBSMILE/tmodloader1.4#19]
when I try start it I get to here 

Terraria Server v1.4.3.6 - tModLoader v2022.9.47.47

1               Earth
n               New World
d <number>      Delete World
m               Mods Menu
b               Mod Browser

Choose World: 1

and hit enter then it goes no where and have tried all the options.

also here my compose file

version: '3'
services:
  tmodloader:
    image: 'jacobsmile/tmodloader1.4:v2022.09.47.47'
    container_name: 'tmodloader'
    stdin_open: true # docker run -i
    tty: true # docker run -t
    ports:
      - "7777:7777"
    expose:
      - "7777"
    environment:
      # Download the Calamity mod and CalamityMusic mod.
      - "TMOD_AUTODOWNLOAD=2824688072,2824688266"
      # Enable the Calamity mod and CalamityMusic mod.
      - "TMOD_ENABLEDMODS=2824688072,2824688266"
      # Shutdown Message and Autosave Interval (In Minutes)
      - "TMOD_SHUTDOWN_MESSAGE=Goodbye!"
      - "TMOD_AUTOSAVE_INTERVAL=15"
      # Server Settings
      - "TMOD_MOTD=Welcome to my tModLoader Server!"
      - "TMOD_PASS=test"
      - "TMOD_MAXPLAYERS=16"
      # The following world settings are only used when generating a new world.
      - "TMOD_WORLDNAME=Earth"
      - "TMOD_WORLDSIZE=2"
      - "TMOD_WORLDSEED=not the bees!"
      - "TMOD_DIFFICULTY=1"
      # (Deprecated) If TMOD_USECONFIGFILE is set to "Yes", it is expected to have a serverconfig.txt mapped. The Server Settings above will be ignored.
      - "TMOD_USECONFIGFILE=No"
    volumes:
      - /home/docker/Tmodloader/worlds/:/home/terraria/.local/share/Terraria/tModLoader/Worlds/
      - /home/docker/Tmodloader/mods/:/home/terraria/terraria-server/workshop-mods/
      # Uncomment the below line if you plan to use a mapped config file. 
      # - "/path/to/config/config.txt:/root/terraria-server/serverconfig.txt"

If you need more files just ask but nothing has gone into the mounts the only file their is the world file that I made and put in their.

also get System.UnauthorizedAccessException: Access to the path '/home/terraria/.local/share/Terraria/tModLoader/Worlds/Earth.wld' is denied.

**Comment by JACOBSMILE** [comment]
Acknowledged, will review.

**Comment by JACOBSMILE** [comment]
Hi, sorry for the delay. I should be able to take a deeper look at this during the upcoming weekend.

**Comment by SirMonkeyBoy** [comment]
When I go back to 2022.09.47.46 it works but the worlds or mods still not in my folders and I have triple checked mount path

**Comment by JACOBSMILE** [comment]
Hi, thanks for the update. I will be reviewing this evening, work has kept me preoccupied.

**Comment by JACOBSMILE** [comment]
Hi, I published a pull request #22 to attempt to fix this issue. Please pull the latest image and see if it works for you now, and report back.

**Comment by SirMonkeyBoy** [comment]
still not working add user: terraria:terraria,  working_dir: /home/terraria/terraria-server and - UPDATE_NOTICE=false but still no luck and have tried without them
