### ISSUE TITLE
The server is not loading the Mods

### ISSUE THREAD

**Issue by NicMan37** [JACOBSMILE/tmodloader1.4#20]
Hi,
i'm having an  issue deploying the container with mods

i'm using portainer to managing the stack. above the compose file

```
version: "3.9"

volumes:
  data:
  workshop:

networks:
  default:
    external: true
    name: game_network

services:
  tmodloader:
    image: jacobsmile/tmodloader1.4
    container_name: TModLoader
    ports:
      - 7777:7777
    expose:
      - 7777
    environment:
      #Boss Checklist, Recipe Browser, Calamity Mod, Calamity Mod Music, Magic Storage, Calamity's Vanities, Thorium Mod, Wing Slot Extra, Which Mod Is This From? (WMITF), Max Stack Plus Extra, Smarter Cursor, Loot Beams, Compare Item Stats, Shop Expander
      TMOD_AUTODOWNLOAD: 2669644269,2619954303,2824688072,2824688266,2563309347,2824688804,2909886416,2597324266,2563851005,2562915378,2877850919,2847872897,2576847291,2828370879
      #Boss Checklist, Recipe Browser, Calamity Mod, Calamity Mod Music, Magic Storage, Calamity's Vanities, Thorium Mod, Wing Slot Extra, Which Mod Is This From? (WMITF), Max Stack Plus Extra, Smarter Cursor, Loot Beams, Compare Item Stats, Shop Expander
      TMOD_ENABLEDMODS: 2669644269,2619954303,2824688072,2824688266,2563309347,2824688804,2909886416,2597324266,2563851005,2562915378,2877850919,2847872897,2576847291,2828370879
      # Shutdown Message and Autosave Interval (In Minutes)
      TMOD_SHUTDOWN_MESSAGE: "Shutting Down"
      TMOD_AUTOSAVE_INTERVAL: 10
      # Server Settings
      TMOD_MOTD: "Welcome!"
      TMOD_PASS: password
      TMOD_MAXPLAYERS: 10
      # The following world settings are only used when generating a new world.
      TMOD_WORLDNAME: World
      TMOD_WORLDSIZE: 3
      TMOD_WORLDSEED: ""
      TMOD_DIFFICULTY: 2
      TMOD_SECURE: 1
      TMOD_NPCSTREAM: 60

    volumes:
      - data:/home/terraria/.local/share/Terraria/tModLoader/Worlds
      - workshop:/home/terraria/terraria-server/workshop-mods
```

it seems it doesn't downloading the mods to the `/home/terraria/terraria-server/workshop-mods` folder
![image](https://user-images.githubusercontent.com/17047602/236784438-a4707dab-9c3c-420a-942a-9aa99121ec29.png)
in the logs i found this 
`Downloaded item 2669644269 to "/home/terraria/Steam/steamapps/workshop/content/1281930/2669644269"`

```
[SYSTEM] Enabling 2669644269...
ls: cannot access '/home/terraria/terraria-server/workshop-mods/steamapps/workshop/content/1281930/2669644269/*/': No such file or directory
```

Best Regards
Manuel

**Comment by JACOBSMILE** [comment]
Acknowledged, will review.

**Comment by JACOBSMILE** [comment]
Hi, sorry for the delay. I should be able to take a deeper look at this during the upcoming weekend.

**Comment by NicMan37** [comment]
hi, i managed to make it run without the docker volumes, using just directory mounting. i think it's a volumes releated problem

**Comment by JACOBSMILE** [comment]
Thanks for the update. I will be reviewing this evening, work has kept me preoccupied.

**Comment by JACOBSMILE** [comment]
Hi, I published a pull request #22 to attempt to fix this issue. Please pull the latest image and see if it works for you now, and report back.

**Comment by NicMan37** [comment]
Hi, this weekend i ll try it

**Comment by miguelrjim** [comment]
I was still having this issue, definitely something related with specifying the volume mapping to `/home/terraria/terraria-server/workshop-mods`, i fixed this by instead mapping to `/home/terraria`, this way it should still keep the downloaded mods in the directory already & it loads properly.

**Comment by ySteini** [comment]
Is there any way to fix now?

**Comment by JACOBSMILE** [comment]
Please review the updated documentation covering some permission requirements on the host to support volume mapping. 

It has been copied below for your reference. (Commit [95a967f](https://github.com/JACOBSMILE/tmodloader1.4/commit/95a967f5d74386daaaab56484281bec29dc6653f))

Permission Configuration
This container uses an account named terraria internally which is a low-privileged user. Due to Unix kernel constraints, it may be necessary to grant UID and GID 1000 access to the mapped world and mod directories to properly launch the server.

To do this easily, perform the following command on your HOST's Mod and World directories:

chown 1000:1000 <directory_path_here> -R
